project:
  type: website

website:
  title: "Models as Prediction Machines"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assets/models_as_prediction_machines.zip
        text: Replication package
      - text: Examples
        menu:
          - href: examples/soep.qmd
            text: "Illustrating target quantities"
          - href: examples/relationship.qmd
            text: "Relationship Status and Friends"
          - href: examples/deskmates.qmd
            text: "Friends by Chance"



format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
