# Models as Prediction Machines

## How to Convert Confusing Coefficients into Clear Quantities

This website hosts a replication package and detailed worked examples to accompany this article:

> "Rohrer, J. M., & Arel-Bundock, V. (2025, August 25). Models as Prediction Machines: How to Convert Confusing Coefficients into Clear Quantities.

You can find the preprint on [PsyArXiv](https://osf.io/preprints/psyarxiv/g4s2a_v1){target="_blank"}, alternative download link [here](https://juliarohrer.com/wp-content/uploads/2025/08/models_as_prediction_machines.pdf){target="_blank"}.

Worked Examples:

0. [Illustrating target quantities](examples/soep.html)

1. [Relationship Status and the Importance of Friends](examples/relationship.html)

2. [Friends by Chance](examples/deskmates.html)


Download the [full replication package as ZIP here.](assets/models_as_prediction_machines.zip)

The material on this site is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). This means that you can freely share and adapt the material, as long as you cite the article listed above.
