---
title: "Example 3: Deskmates"
author: "Julia Rohrer"
date: "`r Sys.Date()`"
format: 
  html:
    toc: true
---

```{r setup, include=FALSE}
source(here::here("scripts/load.R"))
knitr::opts_chunk$set(error = TRUE, echo = TRUE)
```

## Overview

This document contains example 3, in which we analyze the effect of being seated next to each other on friendships, using Bayesian multilevel models.

### Load data and fit model

```{r load_fit}
# Read the data
dat <- read.csv(here("data/deskmates.csv"))
head(dat)

# We will only take part of the data to make the model fitting less tedious
classes <- unique(dat$class_id)

# Total number of classes
length(classes)

# Lets keep 30 of those
classes <- classes[1:60]

# Reduce the data
dat <- dat[dat$class_id %in% classes,]

# Gendermatch as factor
dat$girl_match <- as.factor(dat$girl_match)
dat$deskmate <- as.factor(dat$deskmate)

# Fit the model

set.seed(12345)
mod <- brm(friend ~ deskmate + girl_match + deskmate:girl_match + 
             mean_gpa + diff_gpa + mean_gpa:deskmate + diff_gpa:deskmate +
             (1 |class_id) + (1 | mm(s1, s2)),
           family = bernoulli(link = "logit"),
           data = dat,
           cores = 4)

# Save model fit
saveRDS(mod, file = here("fits/deskmates.rds"))

# Load the fitted model
mod <- readRDS(here("fits/deskmates.rds"))
```

### Model results in marginaleffects

```{r effects}

avg_comparisons(mod, variables = "deskmate", type = "link")

avg_comparisons(mod, variables = "deskmate")

avg_predictions(mod, variables = "deskmate")


avg_comparisons(mod, variables = "deskmate", 
                by = "girl_match")

avg_comparisons(mod, variables = "deskmate", 
                by = "girl_match",
                hypothesis = "(b1 + b3)/2 = b2")

# HIER WEITER

# New categorical difference in GPA variable
dat$diff_gpa_cat <- NA
dat$diff_gpa_cat[dat$diff_gpa <= mean(dat$diff_gpa, na.rm = TRUE) - sd(dat$diff_gpa, na.rm = TRUE)] <- -1
dat$diff_gpa_cat[dat$diff_gpa > mean(dat$diff_gpa, na.rm = TRUE) - sd(dat$diff_gpa, na.rm = TRUE)] <- 0
dat$diff_gpa_cat[dat$diff_gpa >= mean(dat$diff_gpa, na.rm = TRUE) + sd(dat$diff_gpa, na.rm = TRUE)] <- 1

avg_comparisons(mod, variables = "deskmate", 
                by = "diff_gpa_cat")

# Evaluate effect at values of interest
avg_comparisons(mod, variables = c("deskmate", "girl_match"))

avg_comparisons(mod, variables = list("diff_gpa" = "sd"))

avg_comparisons(mod, variables = c("deskmate", "diff_gpa"))

comparisons(mod, variables = "deskmate", newdata = datagrid(diff_gpa = range))


# Compare the effects
comparisons(mod, variables = "deskmate", newdata = datagrid(
  diff_gpa = range), hypothesis = "b1 = b2") # 0.046


# Compare the effects separately by gendermatch
comparisons(mod, variables = "deskmate", newdata = datagrid(
  girl_match = c(0, 1, 2), 
  diff_gpa = range))

comparisons(mod, variables = "deskmate", newdata = datagrid(
  girl_match = c(0, 1, 2), 
  diff_gpa = range), hypothesis = "b1 = b2") # 0.046

comparisons(mod, variables = "deskmate", newdata = datagrid(
  girl_match = c(0, 1, 2), 
  diff_gpa = range), hypothesis = "b3 = b4")

comparisons(mod, variables = "deskmate", newdata = datagrid(
  girl_match = c(0, 1, 2), 
  diff_gpa = range), hypothesis = "b5 = b6")


# Correlation between gender-match and difference in gpa
mean(dat$diff_gpa[dat$girl_match == 0], na.rm = TRUE)
mean(dat$diff_gpa[dat$girl_match == 1], na.rm = TRUE)
mean(dat$diff_gpa[dat$girl_match == 2], na.rm = TRUE)

# How to evaluate interaction between diff_gpa and deskmate, holding constant the other stuff
avg_comparisons(mod, variables = "deskmate", by = "diff_gpa", newdata = datagrid(diff_gpa = range))
avg_comparisons(mod, variables = "deskmate", by = "diff_gpa", newdata = datagrid(diff_gpa = range), hypothesis = "b1 = b2") # difference of 0.0462

avg_comparisons(mod, variables = "deskmate", by = "diff_gpa") # here, the difference in effects is much larger

avg_comparisons(mod, variables = "deskmate", by = "diff_gpa", hypothesis = "b1 = b37") # here, the difference in effects is much larger

```